platform :ios, '8.0'
use_frameworks!
#use_frameworks!个别需要用到它，比如ReactiveCocoa
target 'RACDoubanRequest' do
  pod 'AFNetworking', '~> 3.1’
  pod 'SVProgressHUD', '~> 2.0.3'
  pod 'ReactiveCocoa', '~> 4.2.2'
end
